# Generated by Django 6.0 on 2025-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('to_review', 'To Review'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
    ]
